package dev.shreya.productservice.repositories;

import dev.shreya.productservice.models.Category;
import dev.shreya.productservice.models.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

//give datatype of PK of Product table
public interface ProductRepository extends JpaRepository<Product, Long> {
    Product save(Product p); // the attributes that are automatically
    //  generated by DB will not be in the param, but will be there in
    // returned object example id in case of POST
    List<Product> findAll();

    Product findByIdIs(long id);
//    @Query(value="SELECT * FROM Product  WHERE category.title =?1 "
//            , nativeQuery = true)
    List<Product> findAllByCategoryTitle(String title);
    void deleteById(Long productId);



}
